# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your_account_id>.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=<your_account_id>.dkr.ecr.us-east-1.amazonaws.com/java-docker-app
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - docker build -t java-docker-app .
      - docker tag java-docker-app:latest $REPO_URI:latest
  post_build:
    commands:
      - docker push $REPO_URI:latest

artifacts:
  files: []

