version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "✅ Install phase started"

  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 510001482086.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=510001482086.dkr.ecr.us-east-1.amazonaws.com/hello-app
      - IMAGE_TAG=$REPO_URI:$CODEBUILD_BUILD_NUMBER
      - echo "🔍 Checking OS..."
      - uname -a

  build:
    commands:
      - echo "📁 Moving into app directory"
      - cd jenkins-java-docker-app
      - echo "🛠️ Compiling Java code"
      - javac src/Main.java
      - echo "🐳 Building Docker image"
      - docker build -t hello-app .
      - docker tag hello-app:latest $IMAGE_TAG

  post_build:
    commands:
      - echo "🚀 Pushing Docker image to ECR"
      - docker push $IMAGE_TAG
      - echo "✅ Build and push complete"

artifacts:
  files:
    - '**/*'
