version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 20
    commands:
      - echo "✅ Install phase: Environment ready"

  pre_build:
    commands:
      - echo "🔍 Checking OS..."
      - uname -a

  build:
    commands:
      - echo "📁 Moving into app directory"
      - cd jenkins-java-docker-app
      - echo "🛠️ Compiling Java code"
      - javac src/Main.java
      - echo "🐳 Building Docker image"
      - IMAGE_TAG=jenkins-java-image:$CODEBUILD_BUILD_NUMBER
      - docker build -t $IMAGE_TAG .

  post_build:
    commands:
      - echo "🚀 Running Docker container"
      - docker run -d --name java-jenkins-app -p 8080:8080 jenkins-java-image:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - '**/*'
