pipeline {
    agent { label 'jenkins-slave' }

    environment {
        IMAGE_TAG = "jenkins-java-image:${BUILD_NUMBER}"
        CONTAINER_NAME = "java-jenkins-app"
    }

    stages {
        stage('Check OS') {
            steps {
                sh 'uname -a'
            }
        }

        stage('Clone') {
            steps {
                git 'https://github.com/AbhaySharma0017/devops-learning-journey.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_TAG}", ".")
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker rm -f ${CONTAINER_NAME} || true"
                    sh "docker run -d --name ${CONTAINER_NAME} -p 8080:8080 ${IMAGE_TAG}"
                }
            }
        }
    }
}
